### ISSUE TITLE
Create a Footer Component 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/React-Aura#2]
### TASK : 
- Create a footer component in `./src/Components/Footer/`

**Comment by pooranjoyb** [comment]
Hello @pooranjoyb! Welcome to Team React-Aura! Thanks for raising the issue!<p>Soon the maintainers/owner will review it and provide you with feedback/suggestions.</p>

**Comment by ankitjangidx** [comment]
give little bit more context and assign this issue to me @pooranjoyb

**Comment by Arya-n-101** [comment]
can i do it

**Comment by mohitsaini07** [comment]
Hi @pooranjoyb , I would like to work on this issue if available

**Comment by pooranjoyb** [comment]
> Hi @pooranjoyb , I would like to work on this issue if available

Hey @mohitsaini07 
Would be glad if you'd create a new issue or some feature request. This issue is already assigned to two of 'em. 👍

**Comment by ankitjangidx** [comment]
@pooranjoyb i run this project in my local sys and it is looking like below for now 
![image](https://github.com/pooranjoyb/Hacktoberfest2023/assets/100501722/9e841907-28b1-40f0-ac84-4d27da7abbe4)

can you please tell me what type of footer I need to make because i need little bit text or info of a site, so can you give me some idea ?

**Comment by pooranjoyb** [comment]
As of now, I've just initiated the project by creating a simple `GlassNavbar`
I'd suggest you to create a similar `Footer Component` and add it below the `<GlassNavbar/>` component. 

We'll soon work out with Sidebars and routes for different components 😄 @ankitjangidx

**Comment by pooranjoyb** [comment]
Hey @ankitjangidx please let me know if you're still working on this issue.
If yes, then follow these tasks :
- the `copy code containers` are not scrollable as of now. 
- please make sure you modify them, so that the `containers` are not very large and peers can scroll to see the rest of the component.

**Comment by ankitjangidx** [comment]
ok i will fix it let me work on it @pooranjoyb

**Comment by pooranjoyb** [comment]
> ok i will fix it let me work on it @pooranjoyb

Go ahead 👍 @ankitjangidx

**Comment by Arya-n-101** [comment]
What about excluded ?

**Comment by ankitjangidx** [comment]
> > ok i will fix it let me work on it @pooranjoyb
> 
> Go ahead 👍 @ankitjangidx

also i am thinking i can make more beautiful footer than current let me show you 
![image](https://github.com/pooranjoyb/Hacktoberfest2023/assets/100501722/4f782298-45f9-4f3e-bfcf-9ee4cddfcdea)
should i work on current footer or you like the above one ?

**Comment by pooranjoyb** [comment]
Sure Go ahead 👍

**Comment by ankitjangidx** [comment]
just give me some time I will implement a new footer and a copy icon so that when the user clicks on the copy icon the code of the component will be copied to the user's clipboard.

**Comment by pooranjoyb** [comment]
Okay sure @ankitjangidx
