### ISSUE TITLE
[Bug] : Sidebar hover effect not working on some links 

### ISSUE THREAD

**Issue by ayush-khatrii** [pooranjoyb/React-Aura#24]
When hovering over the sidebar items, there should be noticeable hover effects . But on some items hovering not working.
please assign me this issue

**Comment by pooranjoyb** [comment]
Hello @ayush-khatrii! Welcome to Team React-Aura! Thanks for raising the issue!<p>Soon the maintainers/owner will review it and provide you with feedback/suggestions.</p>
