### ISSUE TITLE
New Breadcrumb Component

### ISSUE THREAD

**Issue by ManishPJha** [pooranjoyb/React-Aura#26]
I am willing to add breadcrumb component.

### what i have done :
- added new component BreadcrumbWithIcon component
- using **tailwind-merge** for conditional styling

### changes preview:

![image](https://github.com/pooranjoyb/React-Aura/assets/93715065/b684793f-f04b-4c8d-b3a0-bbc9411d05c1)

Can I  make a PR for this @pooranjoyb  ?

**Comment by pooranjoyb** [comment]
Hello @ManishPJha! Welcome to Team React-Aura! Thanks for raising the issue!<p>Soon the maintainers/owner will review it and provide you with feedback/suggestions.</p>

**Comment by pooranjoyb** [comment]
Go for it @ManishPJha 🚀

**Comment by ManishPJha** [comment]
> Go for it @ManishPJha 🚀

I've created PR for it please review it 🙏 .
