### ISSUE TITLE
Add more inputs components and button variants

### ISSUE THREAD

**Issue by ANKITy102** [pooranjoyb/React-Aura#8]
I'd like to expand our components library by incorporating additional input components, such as those featuring password icons, email icons, and dropdown inputs. Furthermore, I'd like to introduce an array of new button variants.
<hr/>
@pooranjoyb , kindly assign this issue to me.

**Comment by pooranjoyb** [comment]
Hello @ANKITy102! Welcome to Team React-Aura! Thanks for raising the issue!<p>Soon the maintainers/owner will review it and provide you with feedback/suggestions.</p>

**Comment by ANKITy102** [comment]
@pooranjoyb yes my contribution is marked as excluded.

**Comment by pooranjoyb** [comment]
> @pooranjoyb 
> now is there a chance that this repo will be removed from the excluded list. 

Could be, will have to wait for a day or two.

**Comment by pooranjoyb** [comment]
@ANKITy102 You can still create a PR with this issue. If the problem is fixed then you'll get the accepted label.
